---
title: Landfills in Sub-Saharan Africa A Case Study of Ghana and Kenya
author: Nykol Armacanqui Martinez de Tudor and Labanya Paul

format: 
  html: 
    toc: true
    toc_depth: 2
    self-contained: true
bibliography: bibliography.bib
---

# 1. Research Proposal

## *Motivation*

The staggering reality of over 15 million individuals inhabiting garbage dump communities globally, though likely an under reported figure, highlights a pressing concern. This number is not static; it's steadily increasing (@noauthor_about_2024). Alarmingly, a significant portion of this population, conservatively estimated at two-thirds, resides in the sub-Saharan Africa region alone. The well-being of these individuals, teetering on the edge of poverty, demands urgent attention. In this context, well-being primary refers to wealth, with income serving as a proxy for it.

We aim to analyze how living near landfills affects these communities. These environments are often synonymous with destitution and neglect. By studying this, we hope to improve the lives of those in these communities through informed future policymaking.

## *Research question*

How does proximity to landfills impact the wealth of people living in Ghana and Kenya?

## *Literature overview*

Existing scientific research in Kenya and Ghana investigates the health and environmental impacts of landfill proximities, showing detrimental effects in both the short and long term (@obiri-nyarko_assessment_2021; @lettor_assessing_2018; @mattiello_health_2013; @fazzo_health_2023; @kenneth_kamumbu_mugo_assessment_2015). However, few studies have specifically addressed the relative strength of the impact of income (wealth) for individuals near these sites.

In Kenya, a study aimed to elucidate the relationship between proximity to garbage collection points/landfills and the Quality of Life Index. Employing a Pearson correlation coefficient analysis, the research revealed a noteworthy positive correlation between income levels and proximity to landfills. However, this correlation came at a cost: increased exposure to diseases and a decline in air quality were observed as consequences of such proximity (@wekisa_spatial_2020) . Another study, contributing to the understanding of waste management's socio-economic ramifications, focused on households living near the Dandora dumpsite. Through questionnaire surveys involving 121 households, the research examined two key variables: income from solid waste management and household expenditure. Descriptive and correlation analyses unveiled a substantial finding: the total income derived from solid waste management contributed a significant 82.88% towards the total household expenditure. Moreover, a statistically significant correlation (r=0.389, p=0.01) underscored the interplay between income generated from waste management activities and household financial stability (@wangatia_influence_2011).

Additionally, a study analyzed solid waste management policies in Nairobi and Mombasa, focusing on how the implementation of these policies could shift from a criminal perspective to a regulatory framework. The goal was to demonstrate how effective waste management could create wealth and employment while reducing pollution. The findings revealed that the mechanisms of a top-down approach are not well aligned due to mismanagement, the prevalence of informal and illegal dumpsites, and cartel domination. Consequently, there is a significant gap in successful policy implementation (@haregu_assessment_2017).

In Ghana, various studies have been conducted. One such study investigated the motivations and challenges of informal sector workers in the context of income generation. Employing a mixed-method approach involving interviews and questionnaires, the researchers utilized statistical analysis tools such as the Statistical Package for the Social Sciences (SPSS) followed by Exploratory Factor Analysis (EFA) and Relative Importance Index (RII) to discern patterns and draw conclusions. Their findings suggest that waste pickers may prioritize immediate financial gain over their health due to economic necessity, as evidenced by their willingness to endure short-term and long-term health risks associated with landfill work. This highlights the primacy of survival considerations in shaping the decision-making of informal sector workers (@mensah_transforming_2024).

Another study conducted by Owusu and Sekyere (2018) examined the effects of landfills in Kumasi on economic development. The research used focus groups and in-depth interviews involving stakeholders such as public health departments, employment desks, waste management departments, environmental sanitation offices, as well as households and informal workers. The findings revealed several positive economic impacts associated with landfills, including benefits accruing to waste pickers through the collection of recyclable materials (such as plastics, metals including copper, gold, and silver, and glass), farmers benefiting from cultivatable areas, and homeowners experiencing appreciation in property values due to the construction of access roads for the landfill area. Notably, 90% of respondents reported a positive impact on land value. These results show the role of landfills in job creation and their potential contribution to poverty alleviation within nearby communities, where monetary considerations can outweigh health risks (@fletcher_urban_2016).

Another study looked at the overall role of waste pickers and their contribution to poverty alleviation and the circular economy. It specifically focused on the recycling and reusing, and transformation of electronic and electrical waste. The study examined 45 case studies, as well as online resources and international reports. They found that in developing countries like Ghana, informal waste pickers are significantly increasing due to economic constraints (cutting welfare, rising unemployment, etc.) and an increase in waste generation. Collecting and selling these items contribute to their household income. Waste pickers earn almost US\$2 per day, and in Ghana, scrap dealers can make profits from dismantling, reincorporating into production, and reselling illegally. The study further highlights how this area should be formalized as a way to empower what waste pickers are already doing as a public service (@morais_global_2022). These collective scientific studies show the complex trade-offs between the livelihoods of the most vulnerable and the waste management policies entrusted by the government.

## *Data Description*

Georeferenced data obtained from the Demographic and Health Surveys (DHS) for Ghana and Kenya, employing secondary data sourced from IPUMS DHS databases (@noauthor_ipums-dhs_nodate). The datasets are structured at the household level, collected via questionnaires administered to household members. Our main variable is 'Wealth Index Quantile Household' which serves as a proxy for household income levels. Our other variable is proximity to landfills in both Ghana and Kenya.To map out where the landfills are and how they have changed over time (in terms of size), we use imagery from Google Earth Pro covering 6 years, from 2008 to 2014 (@noauthor_earth_nodate). These variables will help us determine how household wealth (income) has been affected whilst being in close proximity to landfills, with comparison to the control group (using city data). Landfills that are worked on in the beginning stages are:

Ghana -

-   Agbogbloshie landfill, Oti landfill, Gbalahi landfill, Sofokrom landfill, Pantang Borla dumpsite, Awutu Senya dumpsite landfill, Nkanfoa landfill, Sherigu Bolgatanga dumpsite, Wa landfill, Nsumia dumpsite.

Kenya -

-   Dandora Dumpsite, Gioto dumpsite ,Kisumu Municipal garbage site, Mwakirunge dumpsite, Kayole, Nyeri, Thika dumpsite,Kiteezi Landfill and Maputo city landfill.

Out of these landfills, only a few intersected with the DHS city data. These will be worked on in further stages:

Ghana -

-   Agbogbloshie landfill, and Oti landfill.

Kenya -

-   Dandora dumpsite, Maweni landfill, and Kibera landfill.

## *Empirical Strategy*

Setting: The unit of study consists of clusters of households within the Ghana and Kenya region. The households total are 282,836, with Kenya at 192,355 and Ghana at 90,481. Households are dispersed around the country. Landfill areas are calculated between 2008 to 2014, an observation of 6 years. Kenya landfills originally consisted of 7 but only 3 (Dandora, Kibera and Maweni) had intersecting data with cities Nairobi and Mombasa. Ghana landfills originally consisted of 10 but only 2 (Agbogbloshie and Oti) had intersecting data with cities Accra and Kumasi.

Treatment: The treatment group comprises of households living within a set distance of the landfill. This group would be exposed to the effects of landfill proximity, influencing the wealth variable. Distance to landfill is different in every landfill (varying buffer sizes):

Kenya -

-   Dandora: 0.204 ha

-   Kibera: 0.172 ha

-   Maweni: 0.093 ha

Ghana -

-   Agbogbloshie: 0.139 ha

-   Oti: 0.186 ha

Controls: The control group consists of households within a set distance of the city center, which would not be exposed to landfill effects. This allows us to compare the treatment group's wealth to the control group's. Distance to city center is different in every landfill (consistent buffer size + varying ring size):

Kenya -

-   Dandora: 0.093 ha + 0.056 ha = 0.149 ha

-   Kibera: 0.093 ha + 0.019 ha = 0.112 ha

-   Maweni: 0.093 ha + 0.019 ha = 0.122 ha

Ghana -

-   Agbogbloshie: 0.093 ha + 0.074 ha = 0.167 ha

-   Oti: 0.093 ha + 0.006 ha = 0.099 ha

Bias and Identification: A potential bias identified stems from variations in landfill types across Ghana and Kenya. Some landfills are government-maintained and engineered according to specific protocols, while others are informal dumping sites, often termed "illegal," which fail to meet standard regulations and have a more detrimental impact on nearby communities. Furthermore, the presence of a patriarch in a household could confound the experiment, as households with a senior male figure might have a different wealth index compared to those without.

To address this variation, we will employ a Ordinary Least Squares model..

## Bibliography
